[project]
name = "d4"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
d4 = "d4:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
