[project]
name = "d5"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
d5 = "d5:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
